# Generated by Django 4.1.4 on 2022-12-08 20:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveSmallIntegerField(error_messages='серия карты состоит из 4х цифр', validators=[django.core.validators.RegexValidator(regex='^\\d{4}$')], verbose_name='серия')),
                ('numbers', models.PositiveBigIntegerField(verbose_name='номер')),
                ('release_data', models.DateTimeField(auto_now_add=True, verbose_name='дата выпуска')),
                ('term', models.PositiveSmallIntegerField(choices=[('1', '1 месяц'), ('6', '6 месяцев'), ('12', '1 год')], verbose_name='срок')),
                ('end_activity', models.DateTimeField(verbose_name='дата окончания активности')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='сумма')),
                ('is_active', models.BooleanField(default=False, verbose_name='активирована')),
                ('overdue', models.BooleanField(default=False, verbose_name='просрочена')),
                ('is_delete', models.BooleanField(default=False, verbose_name='удалена')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='ProfileCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='\\+7\\d{10,10}$')], verbose_name='телефон')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.card', verbose_name='карта')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='HistoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_use', models.DateTimeField(verbose_name='дата использования')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.card', verbose_name='карта')),
            ],
            options={
                'verbose_name': 'История карты',
                'verbose_name_plural': 'История карты',
                'db_table': 'history_card',
            },
        ),
    ]
