# Generated by Django 4.1.4 on 2022-12-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 месяц'), (6, '6 месяцев'), (12, '1 год')], verbose_name='срок'),
        ),
    ]
