# Generated by Django 4.1.4 on 2022-12-09 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_card_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecard',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='\\+7\\d{10,10}$')], verbose_name='телефон'),
        ),
    ]
