# Generated by Django 4.1.4 on 2022-12-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_profilecard_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='numbers',
            field=models.CharField(max_length=8, unique=True, verbose_name='номер'),
        ),
    ]
