# Generated by Django 4.1.4 on 2022-12-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_card_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilecard',
            options={'ordering': ['id'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
